FROM quay.io/jupyterhub/jupyterhub:latest

RUN pip install --no-cache-dir --break-system-packages \
    oauthenticator \
    dockerspawner \
    httpx

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

WORKDIR /srv/jupyterhub

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
