FROM quay.io/jupyterhub/jupyterhub:4.1

RUN pip install --no-cache-dir \
    oauthenticator \
    dockerspawner \
    httpx

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

WORKDIR /srv/jupyterhub

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
