{{- if or .Values.hub.oidc.clientSecret .Values.hub.hugrSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hugr-hub.fullname" . }}-secrets
  labels:
    {{- include "hugr-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.hub.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.hub.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.hub.hugrSecretKey }}
  HUGR_SECRET_KEY: {{ .Values.hub.hugrSecretKey | quote }}
  {{- end }}
{{- end }}
